# Generated by Django 5.2.5 on 2025-09-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_procedimiento_reserva_duracion_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='procedimientos',
            field=models.ManyToManyField(blank=True, related_name='doctores', to='appointments.procedimiento'),
        ),
    ]
