# Generated by Django 5.2.5 on 2025-09-08 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_doctor_procedimientos'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioSemanalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre de la plantilla de horario (ej. 'Horario de Verano')", max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horario_templates', to='appointments.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='HorarioTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='appointments.horariosemanaltemplate')),
            ],
            options={
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
    ]
