# Generated by Django 5.2.5 on 2025-09-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_horariosemanaltemplate_horariotemplateitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariotemplateitem',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el bloque de horario está activo y debe mostrarse.'),
        ),
    ]
