# Generated by Django 5.2.5 on 2025-09-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_horariotemplateitem_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariosemanaltemplate',
            name='es_activo',
            field=models.BooleanField(default=False, help_text='Indica si esta plantilla es la actualmente activa para el doctor.'),
        ),
        migrations.AlterField(
            model_name='horariosemanaltemplate',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
