# Generated by Django 5.2.5 on 2025-09-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_horariosemanaltemplate_es_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='notas_doctor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
