# Generated by Django 5.2.5 on 2025-09-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimiento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='procedimientos/'),
        ),
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
